apiVersion: apps/v1
kind: Deployment
metadata:
  name: sakila-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: docker.io/restsql/mysql-sakila:0.8.13
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: sakila-db-service
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-app
  template:
    metadata:
      labels:
        app: quarkus-app
    spec:
      containers:
        - name: quarkus
          image: eu.gcr.io/liquid-idiom-410617/quarkus-tutorial:1.0.0-SNAPSHOT
          env:
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:mysql://sakila-db-service:3306/sakila
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: sakila
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: quarkus-service
spec:
  type: LoadBalancer
  selector:
    app: quarkus-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
